//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMVCEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guia()
        {
            this.Trazabilidad = new HashSet<Trazabilidad>();
        }
    
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string DireccionOrigen { get; set; }
        public string TelefonoEmisor { get; set; }
        public string Receptor { get; set; }
        public string DireccionDestino { get; set; }
        public string TelefonoReceptor { get; set; }
        public string TipoPaquete { get; set; }
        public string CiudadDestino { get; set; }
        public double PesoPaquete { get; set; }
        public double ValorEnvio { get; set; }
        public string Observacion { get; set; }
        public long IdSede { get; set; }
        public long IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Sede Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trazabilidad> Trazabilidad { get; set; }
    }
}
