//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMVCEnvios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCEnviosEntities : DbContext
    {
        public MVCEnviosEntities()
            : base("name=MVCEnviosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<EstadoPaquete> EstadoPaquete { get; set; }
        public virtual DbSet<EstadoSede> EstadoSede { get; set; }
        public virtual DbSet<Guia> Guia { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<Trazabilidad> Trazabilidad { get; set; }
    }
}
