//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMVCEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trazabilidad
    {
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Observaciones { get; set; }
        public long IdGuia { get; set; }
        public long IdEstadoPaquete { get; set; }
    
        public virtual EstadoPaquete EstadoPaquete { get; set; }
        public virtual Guia Guia { get; set; }
    }
}
